name: Nightly build

# Trigger the workflow every day at 5 AM (UTC).
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: lf-lang/lingua-franca/.github/workflows/build.yml@master
    with:
      nightly: true
    secrets:
      envPAT: ${{ secrets.NIGHTLY_BUILD }}
