/*
 * generated by Xtext 2.25.0
 */

package org.lflang;


import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.util.Modules2;
import org.lflang.lf.Model;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;

import de.cau.cs.kieler.core.services.KielerLanguage;

/**
 * Initialization support for running Xtext languages without
 * Equinox extension registry.
 *
 * See {@link LFRuntimeModule}, the base Guice module for LF services.
 */
public class LFStandaloneSetup extends LFStandaloneSetupGenerated implements KielerLanguage {

	private final Module module;

	public LFStandaloneSetup() {
		this.module = new LFRuntimeModule();
	}

	public LFStandaloneSetup(Module... modules) {
		this.module = Modules2.mixin(modules);
	}

	@Override
	public Injector createInjector() {
		return Guice.createInjector(this.module);
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public Injector getInjector() {
        return createInjectorAndDoEMFRegistration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Class<? extends EObject>> getSupportedModels() {
        return List.of(Model.class);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<String> getSupportedResourceExtensions() {
        return List.of("lf");
    }
}
